name: 'Setup Go with caching'
description: 'Sets up Go 1.23 and caches Go modules for optimal CI speed'

inputs: {}
outputs: {}

runs:
  using: "composite"
  steps:
    - name: Set up Go 1.23
      uses: actions/setup-go@v4
      with:
        go-version: '1.23'

    - name: Cache Go modules
      uses: actions/cache@v4
      with:
        path: |
          ~/.cache/go-build
          # for future-proofing, add the default GOPATH/pkg/mod
          ~/.go/pkg/mod
        key: ${{ runner.os }}-go-mod-${{ hashFiles('**/go.sum') }}
        restore-keys: |
          ${{ runner.os }}-go-mod-