name: macOS Release

permissions:
  contents: write

on:
  push:
    tags: ['v*']

jobs:
  release:
    # using macos-15 specifically for arm64
    runs-on: macos-15
    steps:
      - name: Checkout Sidekick
        uses: actions/checkout@v4

      - name: Set up Go
        uses: ./.github/actions/setup-go

      - name: Build USearch
        uses: ./.github/actions/build-usearch

      - name: Copy USearch Library and Headers
        run: |
          cp /tmp/usearch/build_release/libusearch_static_c.a libusearch_c.a
          sudo mkdir -p /usr/local/include
          sudo cp /tmp/usearch/c/usearch.h /usr/local/include/

      - name: Setup Node + Build/Test Frontend
        uses: ./.github/actions/setup-node-frontend

      # TODO: bring this back after switching tests from relying on redis to sqlite
      # - name: Run Sidekick Tests
      #   env:
      #     CGO_ENABLED: 1
      #     CGO_LDFLAGS: "-L. libusearch_c.a -lstdc++ -lm"
      #   run: |
      #     go test -test.timeout 30s ./...

      - name: Build CLI
        id: build-cli
        env:
          CGO_ENABLED: 1
          CGO_LDFLAGS: "-L. libusearch_c.a -lstdc++ -lm"
        run: |
          # Extract version from git tag or use commit hash
          VERSION=""
          if [[ $GITHUB_REF == refs/tags/* ]]; then
            VERSION=${GITHUB_REF#refs/tags/}
          else
            VERSION=$(git rev-parse --short HEAD)
          fi

          SIDE="side_macos_arm64_$VERSION"

          go build -ldflags="-X main.version=${VERSION#v}" -o $SIDE sidekick/cli
          echo "SIDE=$SIDE" >> $GITHUB_OUTPUT

      - name: Release
        uses: softprops/action-gh-release@v2
        if: startsWith(github.ref, 'refs/tags/')
        with:
          files: ${{ steps.build-cli.outputs.SIDE }}
