name: macOS Release

permissions:
  contents: write

on:
  push:
    tags: ['v*']

jobs:
  release:
    # using macos-15 specifically for arm64
    runs-on: macos-15
    steps:
      - uses: actions/checkout@v4
      - uses: ./.github/actions/setup-go
      - uses: ./.github/actions/build-usearch
      - uses: ./.github/actions/setup-node-frontend
      - uses: ./.github/actions/run-backend-tests
      - name: Build CLI
        id: build-cli
        env:
          CGO_ENABLED: 1
          CGO_LDFLAGS: "-L. libusearch_c.a -lstdc++ -lm"
        run: |
          # Extract version from git tag or use commit hash
          VERSION=""
          if [[ $GITHUB_REF == refs/tags/* ]]; then
            VERSION=${GITHUB_REF#refs/tags/}
          else
            VERSION=$(git rev-parse --short HEAD)
          fi

          SIDE="side_macos_arm64_$VERSION"

          go build -ldflags="-X main.version=${VERSION#v}" -o $SIDE sidekick/cli
          echo "SIDE=$SIDE" >> $GITHUB_OUTPUT

      - name: Release
        uses: softprops/action-gh-release@v2
        if: startsWith(github.ref, 'refs/tags/')
        with:
          files: ${{ steps.build-cli.outputs.SIDE }}
